### PR TITLE
Styling updates/fixes

### PR DESCRIPTION
**Pull request by corbinb96**
got rid of course number search bar, fixed footer and dropdown menu. attempted to add responsive icons for mobile but we haven't gotten it quite working yet

### CODE REVIEW

**Review by marikaswanberg — APPROVED** [review]
👍 🔢

**Comment by grantal** [comment]
Wait! Don't get rid of the course number search bar! That one works. The normal spirit search is what's broken.

**Comment by corbinb96** [comment]
ok! we will put it back

**Comment by grantal** [comment]
Thanks

**Pull request merged**
